spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      use-suffix: true
      matching-strategy: ant-path-matcher
  config:
    withXml: true
    activate:
      on-profile: dev


miscellaneous:
  config:
    name: 'dev'


db:
  connections:
    -
      driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
      protocol: 'jdbc:sqlserver'
      ip: '192.168.0.12'
      catalog: 'database name'
      login: 'sql authentication login'
      password: 'and password'
      integratedSecurity: false
    -
      driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
      protocol: 'jdbc:sqlserver'
      ip: 'windows authentication hostname'
      catalog: 'local database name'
      integratedSecurity: true
    -
      driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
      protocol: 'jdbc:sqlserver'
      ip: 'windows authentication hostname'
      catalog: 'local database name'
      integratedSecurity: true
    -
      driver-class-name: 'org.h2.Driver'
      protocol: 'jdbc:h2:mem'
      catalog: 'testdb'
      ip: 'localhost'
      login: 'sa'
      password: ''
      integratedSecurity: false

    -
      driver-class-name: 'org.h2.Driver'
      protocol: 'jdbc:h2:tcp'
      ip: 'localhost'
      catalog: '~/test'
      login: 'sa'
      password: ''
      integratedSecurity: false

jpa:
  hibernate:
    enhancer:
      dirtyTracking: false
      lazyInitialization: false
      associationManagement: false
    props:
      -
        show-sql: true
        ddl-auto: create-drop
        dialect: 'org.hibernate.dialect.SQLServer2012Dialect'

server:
  port: 90
  ignoreAcceptHeader: false
  queryParamAcceptName: 'mediaType'
  acceptFromQueryParam: true
  acceptFromExtension: false
  defaultMediaType: 'application/json'
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false